Added compare before update
Tools4everBV/HelloID-Conn-SA-Sync-ActiveDirectory-Groups-To-SelfService-Products pull request #4
Opened 2023-11-08 13:27 UTC by rschouten97

2023-12-22 13:31 UTC, Rick-Jongbloed commented
Please change mailboxes to groups (line 25)

2023-12-22 13:34 UTC, Rick-Jongbloed commented on Sync-AD-Groups-To-Products.ps1
Line 539-542 should be

```
	if (-not[String]::IsNullOrEmpty($ADGroupsFilter)) {
		$adQuerySplatParams = @{
			Filter     = $ADGroupsFilter
			Properties = $properties
		}
	} else {
		$adQuerySplatParams = @{
			Properties = $properties
		}
	}
```

2023-12-22 13:37 UTC, Rick-Jongbloed commented on Sync-AD-Groups-To-Products.ps1
Line 25: In in comment: rename mailboxes to groups

2023-12-22 13:42 UTC, Rick-Jongbloed commented on README.md
line: | $ADGroupsFilter | String value of filter of which AD groups to include | Optional, when no filter is provided ($ADGroupsFilter = "*"), all groups will be queried |

Possibly change this to "If all groups need to be queried,  the filter should be set to "*"

2023-12-22 13:43 UTC, Rick-Jongbloed requested changes
See comments

2024-01-16 10:16 UTC, rschouten97 commented on Sync-AD-Groups-To-Products.ps1
Corrected.

2024-02-28 20:24 UTC, merged